version: "3.0"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simplebank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/simplebank?sslmode=disable
    depends_on:
      - postgres