version: "3"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simplebank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # - DB_SOURCE=postgres://zypwgdad:qfaaZy7k6Xd_Y7xtMwSPG7IIyTuqRWl2@raja.db.elephantsql.com/zypwgdad?sslmode=disable&timezone=Africa/lagos
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/simplebank?sslmode=disable&timezone=Africa/lagos
      - DB_DRIVER=postgres
      - SERVER_ADDRESS=0.0.0.0:9000
      - TOKEN_SYMMETRIC_KEY=12345678901234567890123456789012
      - ACCESS_TOKEN_DURATION =15m
      - REFRESH_TOKEN_DURATION =24h
      - GIN_MODE=release
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]