version: "3.0"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simplebank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplebank
    ports:
      - "9090:9000"
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/simplebank?sslmode=disable
    depends_on:
      - postgres
    # entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    # command: [ "/app/main" ]